import { Inter } from 'next/font/google'
import './globals.css'
import toast, {Toaster} from "react-hot-toast";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Call Center Test',
  description: 'Generated by Vicky',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster/>
        {children}</body>
    </html>
  )
}
